### ISSUE TITLE
Minor Documentation Errors

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/LuAshitacast#11]
Came across some minor spelling/syntax errors in the HTML guides, which are overall excellent by the way thank you.

gfunc.html:
both the gFunc.Disable and Enable function descriptions have double closed parenthesis 

gdata.html:
the gData.GetEquipment() function description has all the of the slots lower cased when they should start with a capital letter

Would it be better to fork/pull request minor stuff like this for you?

**Comment by GetAwayCoxn** [comment]
also on gfunc.html the ClearEquipBuffer is shown to be gData instead of gFunc.

**Comment by ThornyFFXI** [comment]
These errors have been corrected.  If you would rather pull request, you're welcome to, but I aim to keep issue tracker empty so this is no trouble either.  Whatever is easier for you.
