### ISSUE TITLE
gData Weather and WeatherElement Not Incorporating Storm Buffs

### ISSUE THREAD

**Issue by Shinzaku** [ThornyFFXI/LuAshitacast#12]
Environment data for Weather and Weather Element seem to be replicated from Raw Weather and Raw Weather Element with storm buff active
Screenshot is just simple print debug 
![WeatherValues](https://user-images.githubusercontent.com/4511442/149174594-39609323-f356-430c-a248-4dea392bdbc3.png)

**Comment by ThornyFFXI** [comment]
Fixed in 1.15.
