### ISSUE TITLE
Crash on Zone from reading Augment

### ISSUE THREAD

**Issue by Shinzaku** [ThornyFFXI/LuAshitacast#13]
See attached screenshot.
Seems to only crash after zoning; Reloading back up works fine and the sets get swapped properly.
Only crashing on once piece of gear on one set; Taking out this piece of gear in the .lua stops the crashes for now.

Back = { Name = 'Artio\'s Mantle', Augment = { [1] = 'Phys. dmg. taken -10%', [2] = 'Accuracy+20', [3] = 'Attack+20', [4] = '"Store TP"+10', [5] = 'DEX+20' } },
![LuashitacastError](https://user-images.githubusercontent.com/4511442/149644397-57591c23-1a2b-49bf-8958-bfe52ee2979d.png)

**Comment by Shinzaku** [comment]
Ah just found if I moved my unaugmented Artio mantle out of my inventory (put it in my Mog Safe) that also stops the crash

**Comment by ThornyFFXI** [comment]
Fixed in 1.16.
