### ISSUE TITLE
GetPetAction Nil Values for SMN

### ISSUE THREAD

**Issue by Shinzaku** [ThornyFFXI/LuAshitacast#14]
Trying to use gData.GetPetAction() for SMN swaps when using a Blood Pact ability. 
Unable to compare Name, Id, or other values as they are nil
![image](https://user-images.githubusercontent.com/4511442/149824345-6d63442b-50b8-4d0d-b219-e6283498497c.png)

Lua being used under HandleDefault:
```
local petAction = gData.GetPetAction();

  if (petAction ~= nil) then
      print("Name: " .. tostring(petAction.Name));
      print("ActionType: " .. tostring(petAction.ActionType));
      print("Type: " .. tostring(petAction.Type));
      print("Id: " .. tostring(petAction.Id));
      HandlePetAction(petAction);
      return;
  else
      gFunc.EquipSet(sets.Idle);
  end
```
Not sure if I'm doing something wrong with reading the pet action data

**Comment by ThornyFFXI** [comment]
Fixed in 1.21.
