### ISSUE TITLE
BST Pet Ready move "Wild Carrot" doesn't seem to trigger a GetPetAction()

### ISSUE THREAD

**Issue by dwardlow** [ThornyFFXI/LuAshitacast#15]
The high level Rabbit Jugpets (Lucky Lulush / Droopy Dortwin / Pondering Peter etc) have an AoE HP Restoration move called "Wild Carrot" which scales in potency based on the Pet's Current TP.

The initial trigger for this Ready move seems to be picking up in LuAshitaCast as a PlayerAction just fine... so any Precast gear changes (Desultor Tassets etc) work perfectly. However whenever the Pet actually gets around to using the associated move a second or two later, it doesn't appear to be triggering any PetActions... which means that Midcast gear changes (Nukumi Manoplas +1 etc) aren't able to kick in.

As an illustration: the below abridged LUA profile only throws the string "Wild Carrot" into the chatlog once (on player action activation)... but for other Ready moves it throws their ability name into the chat log at least twice (once on player action activation and then again during pet action activation). 

```
profile.HandleDefault = function()
    local petAction = gData.GetPetAction();
    if (petAction ~= nil) then
        gFunc.Error(petAction.Name);
    end
end
profile.HandleAbility = function()
    local playerAction = gData.GetAction();
    gFunc.Message(playerAction.Name);
end
```

(Thanks for your work on this BTW, was nice to find an equipment swapping addon which works with Ashita v4!) :)

**Comment by ThornyFFXI** [comment]
Are you able to confirm whether this issue is on retail, private servers, or both?

**Comment by dwardlow** [comment]
Retail (Ragnarok server) is where I've been using this addon + seeing the above issue.
It seems to be only affecting "healing" pet moves such as the Rabbit's Wild Carrot and Dhalmel's Healing Breeze... other "buffs" and "attacks" are working fine.

(The only private server I have is a heavily customised Darkstar ToAA fork from ~5 years back which is probably not a great test case; and IIRC doesn't have many Jugpets beyond the Lv75 era implemented anyway!)

Example screenshot #1 (READY - PonderingPeter JugPet's Wild Carrot)
![image](https://user-images.githubusercontent.com/21171687/197419779-592ea87e-9009-4c9e-b953-472a9bbdbb51.png)

Example screenshot #2 (SIC - Dhalmel Charmed Pet's Healing Breeze)
![image](https://user-images.githubusercontent.com/21171687/197419790-133c8488-e0ba-4483-9278-2a4aea47a68c.png)

For comparison (READY - PonderingPeter regular damaging attack "Foot Kick"  (note the RED ERROR TEXT and gearswap into Nakumi Manoplas kicking in for MidCast)
![image](https://user-images.githubusercontent.com/21171687/197419939-ec1931fe-0fb7-48e6-a8a8-687637f41122.png)

For comparison (SIC - Dhalmel pet's non-damaging buff "Berserk")
![image](https://user-images.githubusercontent.com/21171687/197420034-ca280130-137f-474d-81e9-7d773167a1ba.png)

**Comment by ThornyFFXI** [comment]
That should be sufficient data to reproduce and solve this issue.  I'll grab some jugs tomorrow and take a look.

**Comment by ThornyFFXI** [comment]
After looking into this, it appears that Wild Carrot is effectively instant.  The packets for readying and completing arrive in the same communication on retail, meaning that by the time you have a chance to react to it the HP is already gained.  You can actually see this in real time, the pet's HP increases instantly as soon as the ready message appears.

LAC is correctly detecting the ability's start, but also registering the finish immediately after, so no HandleDefault occurs while the ability is pending.  There is no solution here that will allow precast and midcast, you will have to decide in the ability section if you want the Nukumi Manoplas.
