### ISSUE TITLE
Duplicate command sent when using LuAshitaCast (on HorizonXI)

### ISSUE THREAD

**Issue by TheNameless1999** [ThornyFFXI/LuAshitacast#25]
I am having an issue with the LuAshitaCast addon where about 30% of the time, when I use Ready on my Beastmaster, the command is sent twice to the server which causes twice the charges to be used.

- I used in-game macro (not spamming it) and text command, happens with both
- I have tried using the /bstpet # and the /pet <Ability Name> commands, happens with both
- I have tried disabling every addon and tested them one by one
- Without LuAshitaCast loaded, I never experienced a duplicate
- I feel like this might be related to the changes made on HorizonXI to recover from packet losses (mid Jan)

**Comment by TheNameless1999** [comment]
[BST.txt](https://github.com/ThornyFFXI/LuAshitacast/files/10772392/BST.txt)
BST lua profile

**Comment by ThornyFFXI** [comment]
This is almost certainly not solely an ashitacast issue.  The way ashita injects packets could result in an injected packet having a higher sequence id than it should have, which would allow a resent packet to show up to the server as unique.  This is also true of gearswap on windower, and of both on retail.  However, the server should not allow you to use the ability again until the ability completes the first time, so if it were functioning properly you would just receive a message stating you cannot use the ability at this time, like retail.  As a result, I would classify this as intended behavior for LAC, and a bug for Horizon.
