### ISSUE TITLE
gfunc.Combine (and maybe more) are case sensitive

### ISSUE THREAD

**Issue by WinterSolstice8** [ThornyFFXI/LuAshitacast#27]
Consider the following sets:

```
sets.Jump = {
    head = "something",
}

sets.HighJump = gFunc.Combine(sets.Jump, {
    Legs = "something else",
})
```
gFunc.Combine will fail to combine `head` into the `sets.HighJump` set because it's expecting slots to have a leading uppercase letter, such as `Head`.
Additionally, if `Legs` were lowercase that item would also not appear in the resulting `sets.HighJump` set

**Comment by ThornyFFXI** [comment]
This should be fixed, at least for combine, in 1.56.
