### ISSUE TITLE
/lac set causes crash when calling invalid set

### ISSUE THREAD

**Issue by Sippius** [ThornyFFXI/LuAshitacast#3]
Looks like sets are case sensitive as well. I don't have ashitacast loaded at the moment to confirm, but I don't recall it being case sensitive. Might be worth noting in the documentation.

Docs note that Profile members are case sensitive, but I didn't notice any stating set names are case sensitive.

**Comment by ThornyFFXI** [comment]
Both parts of this should be fixed in 1.01.  Thank you again for all the reports, I really appreciate the feedback and most of these fixes are easy, so you're helping make a better addon for everyone by contributing them.

**Comment by ThornyFFXI** [comment]
Sorry, to further clarify: case sensitivity is no longer applicable from '/lac set'.  Lua variable names are case sensitive, and that's a limitation of the lua language that will not be addressed.
