### ISSUE TITLE
Can't equip Joyeuse as BLU in CatsEye server

### ISSUE THREAD

**Issue by kelppo** [ThornyFFXI/LuAshitacast#31]
In CatsEye BLUs are allowed to equip Joyeuse but because of this check: https://github.com/ThornyFFXI/LuAshitacast/blob/main/addons/luashitacast/equip.lua#L163 luashitacast isn't equipping it, I've tried commenting it out and Joyeuse gets equipped correctly, is it possible to make this a setting?

**Comment by ThornyFFXI** [comment]
I am not willing to make this a setting, as it would result in retail players sending inappropriate packets.  The dats that control item data are well enough known that a well maintained private server should be updating them to reflect custom changes like this.  Doing it through the dat would both solve the issue for luashitacast and other plugins, but fix the display element ingame to show the correct jobs.

**Comment by kelppo** [comment]
That's weird then because I'm pretty sure the CatsEye devs updated their dats, here's how it looks in game:

![2023-05-22-235045_441x126_scrot](https://github.com/ThornyFFXI/LuAshitacast/assets/10489620/b35efdff-5b55-47c0-a6e8-bb447dd028e2)

**Comment by ThornyFFXI** [comment]
If your dats are provided via a ffxipivot layer, make sure you have the latest version of ffxipivot to allow ashitas resource manager to reflect them.  The setting was only added recently.  Alternatively, you could replace the actual dat in the install, though I recommend the pivot approach.

**Comment by kelppo** [comment]
I just updated pivot and I'm happy to report that it works now, thanks for the help!
