### ISSUE TITLE
Player MaxMP from gData.GetPlayer() does not update value when gear is swapped.

### ISSUE THREAD

**Issue by Rumthorp** [ThornyFFXI/LuAshitacast#36]
When gData.GetPlayer().MaxMP is called in HandleDefault, HandlePrecast or HandleMidcast after using luashitacast to swap to a set that grants a different MaxMP the new value is not updated. Strangely gData.GetPlayer().MP is updated. Stranger still MaxMP is updated when the status or equipment menu is opened.

I'm not sure if this is a bug or just a quirk of how FFXI works but it is causing problems in my luas. Is there a way to force MaxMP to updated via lua code?

**Comment by ThornyFFXI** [comment]
You cant force max mp to update constantly because server doesnt send that data unless certain menus are opened.  If a few points inaccurate is ok, you can use 100/mpp and multiply by current mp since current and % do update in (nearly) real time.

**Comment by ThornyFFXI** [comment]
But, changes from precast to midcast or other tightly timed measurements still arent going to work since server has to respond to update those.  If you need truly real time numbers, you would have to map the effect of your gear and use that to calculate.

**Comment by Rumthorp** [comment]
Hey, thanks for the speedy response! I'll try using MPP like you suggested. Didn't realize that updated as fast as current mp
