### ISSUE TITLE
BST Pet Skill Names Incorrect (GetPetAction)

### ISSUE THREAD

**Issue by Shinzaku** [ThornyFFXI/LuAshitacast#4]
Testing out comparing the pet action, and the Name field is returning invalid values.

For example with Headbreaker Ken (dragonfly pet)
"Cursed Sphere" returns "Earth Breath"
"Venom" returns "Aqua Breath"
"Somersault" returns "Tidal Wave"

**Comment by ThornyFFXI** [comment]
Fixed in 1.03.  Thank you!
