### ISSUE TITLE
Black Background if we send command too fast to the server after zoning

### ISSUE THREAD

**Issue by nxnslite** [ThornyFFXI/LuAshitacast#40]
while doing some test. I came across a problem
while using luashitacast and nomad at the same time.

when zoning in a town I wanted to activate nomad but doing it using profile.HandleDefault send the packet too fast and we get a black background / cannot move about 60% of the time.. reloading a zone twice could help loading it correctly.

FIX: Adding a little delay to profile.HandleDefault  after zoning.

example:
'
nomad_active = false

Nomad_List` = {"Aht Urhgan Whitegate","The Colosseum","Nashmau","Southern San d'Oria [S]","Throne Room [S]","Windurst Waters [S]","Chateau d'Oraguille","Northern San d'Oria","Port San d'Oria","Southern San d'Oria","Heaven's Tower","Port Windurst","Windurst Walls","Windurst Waters","Windurst Woods","Bastok Markets","Bastok Mines","Metalworks","Port Bastok","Lower Jeuno","Port Jeuno","Ru'Lude Gardens","Upper Jeuno","Selbina","Mhaura","Tavnazia","Kazham","Norg","Rabao","Tavnazian Safehold","Western Adoulin","Eastern `Adoulin"};

profile.HandleDefault = function()
      nomad(enviro.Area)
end

function nomad(zone)
		for _, nomadZone in ipairs(Nomad_List) do
			if (zone == nomadZone) then
				if not nomad_active then
					nomad_active = not nomad_active
					local nomadCommand = nomad_active and '/nomad on' or '/nomad off'
					AshitaCore:GetChatManager():QueueCommand(1, nomadCommand)
				end
			end
		end
end

this could be fix by making profile.handledefault wait 1 second after receiving a packet 0xA

zoneDone = os.time()
zoneStart = os.time()

ashita.events.register('packet_in', 'packet_in_cb', function (e)
	if e.id == 0xA then
		nomad_active = false
		zoneStart = os.time()
		zoneDone = zoneStart + 1
	end
end);

and then add that variable to Handle
profile.HandleDefault = function()
	if os.time() >= zoneDone then
      --code here
        end
end
'

**Comment by ThornyFFXI** [comment]
HandleDefault is for setting up your default equipment gear.  It is not, in any way whatsoever, designed for this sort of automation.  You should either build this into nomad or use a different addon to manage it.  There is zero chance a patch of this sort will be added to LAC to support improper use of the system.
