### ISSUE TITLE
Augment gear loading incorrectly

### ISSUE THREAD

**Issue by Sippius** [ThornyFFXI/LuAshitacast#5]
I have 2 versions of Taeon tabard as follows:
        body = { Name = 'Taeon Tabard', Augment = '"Fast Cast"+5' },
        body = { Name = 'Taeon Tabard', Augment = { [1] = 'Pet: Rng. Acc.+22', [2] = 'Pet: Damage taken -4%', [3] = 'Pet: Accuracy+22', [4] = 'Pet: "Dbl. Atk."+5' } },

The fast cast version is always loading. They are in the same wardrobe and the fast cast version shows up below the other in the list.

To isolate the issue, I took an empty profile and added 2 sets using /lac addset with the body different in each set (other gear is also in the set. One set is called pet and the other set is called fc. I then used /lac set to switch between them. I also tried /lac naked, /lac enable, /lac set <set>. The fast cast body is always loaded regardless of set selected.

**Comment by Sippius** [comment]
Some additional experiments
- moving pet body to inventory doesn't change the results
- moving fc body to inventory causes pet body to be selected all the time
- changing body from fc to pet with an active idle rule does not switch back to fc body

**Comment by ThornyFFXI** [comment]
Won't have a chance to verify and address this until either tomorrow or friday, but noting that I've seen it and consider it a priority issue deserving of attention ASAP.  Thank you for reporting.

**Comment by ThornyFFXI** [comment]
If you want to try an untested fix, change 'Augments' to 'Augment' and .Augments to .Augment on lines 39 and 40 of equip.lua.  I believe this is the culprit.  Will take the time to properly test it and push a fix tomorrow.

**Comment by Sippius** [comment]
No rush on my side, just sharing issues I run across. :)
I'll give your fix a try tonight if I get a chance.
Appreciate all of you effort.

**Comment by Sippius** [comment]
Did some quick experiments and looks to be working as expected with the changes.

**Comment by ThornyFFXI** [comment]
Should be fixed in 1.05.
